#COUNIT_HOME=...

COUNIT_SRCDIR=$(COUNIT_HOME)/src
COUNIT_INCDIR=$(COUNIT_HOME)/include
COUNIT_BINDIR=$(COUNIT_HOME)/bin
COUNIT_OBJDIR=$(COUNIT_HOME)/obj

COUNIT_TESTDIR=$(COUNIT_HOME)/tests

CXXTESTDIR=$(COUNIT_HOME)/cxxtest

INCDIR=-I$(COUNIT_HOME)/glog/include -I$(COUNIT_INCDIR) -I$(BOOST_ROOT)
LIBDIR=-L$(COUNIT_HOME)/glog/lib -L$(COUNIT_BINDIR)
LIBS=-lpthread -lglog

DEFINES=-DDPOR
