#!/bin/bash

export CONCURRIT_HOME=$HOME/Repository/Dropbox/concurrit
export CONCURRIT_TPDIR=$CONCURRIT_HOME/third_party

export LD_LIBRARY_PATH=$CONCURRIT_HOME/lib/:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$CONCURRIT_HOME/lib/:$DYLD_LIBRARY_PATH

# gflags
export LD_LIBRARY_PATH=$CONCURRIT_TPDIR/gflags/lib/:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$CONCURRIT_TPDIR/gflags/lib/:$DYLD_LIBRARY_PATH

# glog
export LD_LIBRARY_PATH=$CONCURRIT_TPDIR/glog/lib/:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$CONCURRIT_TPDIR/glog/lib/:$DYLD_LIBRARY_PATH

# gtest
export LD_LIBRARY_PATH=$CONCURRIT_TPDIR/gtest/lib/:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$CONCURRIT_TPDIR/gtest/lib/:$DYLD_LIBRARY_PATH

# pth
export LD_LIBRARY_PATH=$CONCURRIT_TPDIR/pth/lib/:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$CONCURRIT_TPDIR/pth/lib/:$DYLD_LIBRARY_PATH

# tbb
export LD_LIBRARY_PATH=$CONCURRIT_TPDIR/tbb/lib/ia32/cc4.1.0_libc2.4_kernel2.6.16.21/:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$CONCURRIT_TPDIR/tbb/lib/ia32/cc4.1.0_libc2.4_kernel2.6.16.21/:$DYLD_LIBRARY_PATH

# boost
export BOOST_ROOT=$HOME/Repository/Research/ParLab/Boost/boost_1_48_0
export BOOST_PATH=$BOOST_ROOT
